apiVersion: v1
kind: ConfigMap
metadata: 
  name: frontend
  #namespace: expense
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    pid /var/run/nginx.pid;

    events {
      worker_connections 768;
    }

    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
      client_max_body_size 100m;

      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log warn;

      gzip on;
      gzip_disable "msie6";

      server {
        listen {{ .Values.configMap.port }};
        server_name localhost;

        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
        }

        location /api/ {
          proxy_pass http://backend:8080/;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
          root /usr/share/nginx/html;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  #namespace: expense
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: manikantarouthu/frontendend:v1.0   # ✅ fixed image
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: frontend
          items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  #namespace: expense
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: expense
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080







































